project:
  type: website
  output-dir: docs

website:
  title: "Welcome to Vincent's home!"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Vincent0153
format:
  html:
    theme:
      light: default
      dark: cyborg
    css: styles.css


links:
  - icon: github
    href: https://github.com/Vincent0153





